### ISSUE TITLE
Force flag not working

### ISSUE THREAD

**Issue by perllaghu** [meltwater/puppet-cpan#25] opened 2015-07-15 13:39 UTC
Using Puppet to create a Virtual Machine using the Vagrant infrastructure

Puppet-CPAN version 1.5.0

Workstation Host: Ubuntu/Mint; puppet 3.4.3; Perl 5.18.2
VM: Centos 7; puppet version 3.7.4; Perl version 5.16.3

*Puppet file:

    class foo {
      include cpan
      # This is "chaining" - the sequence has to follow the arrows,
      # and if one fails, it all stops there...
      cpan { 'IRI' :
          ensure  => present,
          require => Class['oricpanmodules'],
        }->cpan { 'RDF::Trine' :
         ensure  => present,
          require => Package['raptor2']
        }->cpan {'RDF::Trine::Model' :
          ensure => present,
        }->cpan {'RDF::Trine::Parser' :
          ensure => present,
        }->cpan {'RDF::Trine::NamespaceMap' :
          ensure => present,
        }->cpan {'RDF::Trine::Serializer::Turtle' :
          ensure => present,
        }->cpan {'RDF::Trine::Serializer::RDFJSON' :
          ensure => present,
        }->cpan {'RDF::Trine::Serializer::RDFXML' :
          ensure => present,
        }->cpan { 'RDF::Lazy' :
          # Note: RDF::Lazy 0.081 fails tests under Perl 5.16 & later
          # Requires the --force flag
          ensure  => present,
          require => Class['::cpan'],
          force => true,
        }
    }

The `RDF::Lazy` module is known to fail it's tests under Perl 5.16, however the code itself is fine.

If I ssh onto the Vagrant box, and install the module directly, it goes:

    [vagrant@ori-devel ~]$ sudo cpan RDF::Lazy
    CPAN: Storable loaded ok (v2.45)
    .......
    Failed 1/11 test programs. 6/100 subtests failed.
    .......
    Running make install
       make test had returned bad status, won't install without force

verses

    [vagrant@ori-devel ~]$ sudo cpan -f RDF::Lazy
    CPAN: Storable loaded ok (v2.45)
    .........
     VOJ/RDF-Lazy-0.081.tar.gz
      /usr/bin/make install  -- OK

So this makes me think there's an issue with the `cpan` module and the `force` flag

**Comment by salimane** [comment] 2016-08-12 12:00
closing this since it's a duplicate of #8

**Closed by salimane** 2016-08-12 12:00 UTC
